name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Login to Apify CLI
        run: apify login --token ${{ secrets.APIFY_TOKEN }}
      - name: Deploy to Apify
        run: apify push --token ${{ secrets.APIFY_TOKEN }}
